### ISSUE TITLE
Error: Transaction too large for fee policy

### ISSUE THREAD

**Issue by nerdcorenet** [GarlicoinOrg/Garlicoin#95]
Expected behaviour:
Broadcast a signed transaction to send the specified amount of GRLC to the specified address using CLI command "sendtoaddress".

Actual behaviour:
```
$ garlicoin-cli sendtoaddress [REDACTED] 1000 "comment_to"
error code: -4
error message:
Transaction too large for fee policy
```

How reliably:
Every time. Cannot sign a tx for 1000 GRLC.

Version:
garlicoin-0.18.0 self-compiled on Ubuntu 20.04

Linux 5.4.x/amd64
Ubuntu 20.04.6

### What version of garlicoin-core are you using?

0.18.0 self-compiled

### Machine specs:
- OS: Ubuntu 20.04.6
- CPU: amd64
- RAM: 32GiB
- Disk size: plenty
- Disk Type (HD/SDD): all

### Any extra information that might be useful in the debugging process.

Nothing relevant added in debug.log.
```
error code: -4
error message:
Transaction too large for fee policy
```
I am able to sign and broadcast a tx for 100 GRLC, but not for 1000.

**Comment by ryan-shaw** [comment]
This happens when there are too many UTXO inputs for the transaction, I can't recall the exact limitations but this is the error you get when you reach them... this is due to mining paying it small amounts, to resolve this the best way is to send the largest amount you can to your own address to consolidate the UTXOs.

More info: https://www.xverse.app/blog/utxo-management#:~:text=UTXO%20consolidation%20is%20the%20process,the%20management%20of%20your%20funds.
